/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 36.2.0 Fri Mar 12 22:06:34 2021.
 */

#include <string.h>

#include "example.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int example_foo_pack(
    uint8_t *dst_p,
    const struct example_foo_t *src_p,
    size_t size)
{
    uint16_t current;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    current = (uint16_t)src_p->current;
    dst_p[0] |= pack_left_shift_u16(current, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(current, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);

    return (4);
}

int example_foo_unpack(
    struct example_foo_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t current;

    if (size < 4u) {
        return (-EINVAL);
    }

    current = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    current |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->current = (int16_t)current;
    dst_p->voltage = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

int16_t example_foo_current_encode(double value)
{
    return (int16_t)(value / 0.0625);
}

double example_foo_current_decode(int16_t value)
{
    return ((double)value * 0.0625);
}

bool example_foo_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint16_t example_foo_voltage_encode(double value)
{
    return (uint16_t)(value / 0.000976562);
}

double example_foo_voltage_decode(uint16_t value)
{
    return ((double)value * 0.000976562);
}

bool example_foo_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int example_bar_pack(
    uint8_t *dst_p,
    const struct example_bar_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->two, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->one, 6u, 0xc0u);
    dst_p[1] |= pack_left_shift_u8(src_p->three, 3u, 0x38u);
    dst_p[1] |= pack_left_shift_u8(src_p->four, 1u, 0x06u);
    dst_p[3] |= pack_left_shift_u8(src_p->five, 6u, 0x40u);

    return (8);
}

int example_bar_unpack(
    struct example_bar_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->two = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->one = unpack_right_shift_u8(src_p[1], 6u, 0xc0u);
    dst_p->three = unpack_right_shift_u8(src_p[1], 3u, 0x38u);
    dst_p->four = unpack_right_shift_u8(src_p[1], 1u, 0x06u);
    dst_p->five = unpack_right_shift_u8(src_p[3], 6u, 0x40u);

    return (0);
}

uint8_t example_bar_two_encode(double value)
{
    return (uint8_t)(value / 0.39);
}

double example_bar_two_decode(uint8_t value)
{
    return ((double)value * 0.39);
}

bool example_bar_two_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t example_bar_one_encode(double value)
{
    return (uint8_t)(value);
}

double example_bar_one_decode(uint8_t value)
{
    return ((double)value);
}

bool example_bar_one_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t example_bar_three_encode(double value)
{
    return (uint8_t)(value);
}

double example_bar_three_decode(uint8_t value)
{
    return ((double)value);
}

bool example_bar_three_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t example_bar_four_encode(double value)
{
    return (uint8_t)(value);
}

double example_bar_four_decode(uint8_t value)
{
    return ((double)value);
}

bool example_bar_four_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t example_bar_five_encode(double value)
{
    return (uint8_t)(value);
}

double example_bar_five_decode(uint8_t value)
{
    return ((double)value);
}

bool example_bar_five_is_in_range(uint8_t value)
{
    return (value <= 1u);
}
